/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Arkify (https://sketchfab.com/arkify)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/doc-martens-boot-3d-scan-no-texture-c1acf32c22f647bfb0c128fef2e632e8
title: Doc Martens Boot 3D Scan (No Texture)
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_49: THREE.Mesh;
  };
  materials: {
    Default_OBJ: THREE.MeshStandardMaterial;
  };
};

/** glbファイルのパス */
const ModelPath = '/assets/martens-boot.glb';

export const Model: React.FC = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(ModelPath) as GLTFResult;

  /* eslint-disable react/no-unknown-property */
  return (
    <group {...props} dispose={null} position={[0, 0, 0]}>
      <group
        position={[0, 0, 0]}
        rotation={[0, 0.6, 0]}
        scale={[0.01, 0.01, 0.01]}
      >
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_32.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_33.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_35.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_36.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_39.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_41.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_42.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_43.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_44.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_45.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_46.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_47.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_48.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_49.geometry}
          material={materials.Default_OBJ}
        />
      </group>
    </group>
  );
};

useGLTF.preload(ModelPath);
